name: Build HTML and Docker Image

on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/pandoc-docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t vaio-html .
      - name: Compose up (devcontainer)
        run: docker compose -f .devcontainer/docker-compose.yml up -d
      - name: Check HTML with curl
        run: |
          sleep 5
          curl -sSf http://localhost:8080 | grep '<html'
      - name: Compose down
        if: always()
        run: docker compose -f .devcontainer/docker-compose.yml down
