name: Build HTML and Docker Image

on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/pandoc-docker.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compose up (devcontainer)
        run: docker compose -f .devcontainer/docker-compose.yml up -d
      - name: Check HTML with curl
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080 | grep '<html'; then
              echo "HTML found"
              exit 0
            fi
            sleep 1
          done
          echo "ERROR: HTML not found after 30 seconds"
          exit 1
      - name: Compose down
        if: always()
        run: docker compose -f .devcontainer/docker-compose.yml down
